# Generated by Django 2.1.7 on 2019-03-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_muiscmodelmobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MuiscModelMobile',
            new_name='MusicModelMobile',
        ),
    ]
